
const ip = 'http://localhost:3001';

export const environment = {
    roleapiUrl: `${ip}/users/getrole`,
    authURL: `${ip}/authentication/auth`,
    getuserURL: `${ip}/users/getuser`,
    fooditemapiUrl: `${ip}/users/getfooditem`,
    placUrl: `${ip}/users/getplacetovisit`,
    registerURL: `${ip}/users/adduser`,
    // bookingURL: `${ip}/booking/addbooking`,
    booking: `${ip}/booking/addbookingwithchild`,
    logic: `${ip}/logic/getlogicall`,
    bookingCancel: `${ip}/booking/bookingcancel`,
    phonenumVerfiy: `${ip}/email/emailverify`,
    idbookingproof: `${ip}/booking/idbookingproof`,
    getbookingwithuserid: `${ip}/booking/getbookingwithuserid?userid=`,
    getbookingwithuseridonly: `${ip}/booking/getbookingwithuseridonly?userid=`,
    getuserwithuserid: `${ip}/users/getuserwithuserid?userid=`,
    changepassword: `${ip}/users/newchangepassword`,
    getcanceledbooking: `${ip}/booking/getcanceledbooking?userid=`,
    checkinconfirm: `${ip}/booking/checkinconfirm`,
    getguestdetail: `${ip}/users/getguestdetail?checkin=`,
    roomtype: `${ip}/room/roomtype`,
    updateuser: `${ip}/users/updateuser`,
    addcontact: `${ip}/users/addcontact`,
    getlogic: `${ip}/logic/getlogic?adult=`,
    addadult: `${ip}/logic/addadult`,
    // `${ip}/logic/getlogic?adult="+adult+"&checkin="+checkIn+"&checkout="+checkOut`,
    actualcheckout: `${ip}/booking/actualcheckout`,
    cancelpolicy: `${ip}/booking/cancelpolicy`,
    forgotpassword: `${ip}/users/forgotpassword`,
    generateOTP: `${ip}/email/generateOTP?email=`,
    verifyOTP: `${ip}/email/verifyOTP`,
    verifyOTPwithemail: `${ip}/email/verifyOTP`,
    getChargedAmenities: `${ip}/booking/getChargedAmenities`,
    getguestbookingstatuscancel: `${ip}/users/getguestbookingstatuscancel?checkin=`,
    getroomslist: `${ip}/room/getroomslist?bookingid=`,
    getroom: `${ip}/room/getroom`,
    getstatus: `${ip}/room/getstatus?stastustype=`,
    roomupdatestatus: `${ip}/room/roomupdatestatus`,
    getroomlist: `${ip}/booking/getroomlist?adults=`,
    getidproofimage: `${ip}/booking/getidproofimage?bookingid=`,
    addebreading: `${ip}/eb/addebreading`,
    getebdata: `${ip}/eb/getebdata`,
    updateebreading: `${ip}/eb/updateebreading`,
    getebreading: `${ip}/eb/getebreading?bookingid=`,
    getguestdetailmonthly: `${ip}/users/getguestdetailmonthly?checkin=`,
    gettariffamount: `${ip}/users/gettariff`,
    updateTariff: `${ip}/users/updatetariff`,
    checkRoomAvailable: `${ip}/room/checkAvailability?roomtypeid=`
  };



  
// export const environment={
// roleapiUrl:'${ip}/users/getrole',
// authURL:`${ip}/authentication/auth`,
// getuserURL:'http://localhost:3001/users/getuser',
// fooditemapiUrl:'http://localhost:3001/users/getfooditem',
// placUrl:'http://localhost:3001/users/getplacetovisit',
// registerURL:'http://localhost:3001/users/adduser',
// // bookingURL:'http://localhost:3001/booking/addbooking',
// booking:'http://localhost:3001/booking/addbookingwithchild',
// logic:'http://localhost:3001/logic/getlogicall',
// bookingCancel:'http://localhost:3001/booking/bookingcancel',
// phonenumVerfiy:'http://localhost:3001/email/emailverify',
// idbookingproof:'http://localhost:3001/booking/idbookingproof',
// getbookingwithuserid:'http://localhost:3001/booking/getbookingwithuserid?userid=',
// getbookingwithuseridonly:'http://localhost:3001/booking/getbookingwithuseridonly?userid=',
// getuserwithuserid:'http://localhost:3001/users/getuserwithuserid?userid=',
// changepassword:'http://localhost:3001/users/newchangepassword',
// getcanceledbooking:'http://localhost:3001/booking/getcanceledbooking?userid=',
// checkinconfirm:'http://localhost:3001/booking/checkinconfirm',
// getguestdetail:'http://localhost:3001/users/getguestdetail?checkin=',
// roomtype:'http://localhost:3001/room/roomtype',
// updateuser:'http://localhost:3001/users/updateuser',
// addcontact:'http://localhost:3001/users/addcontact',
// getlogic:'http://localhost:3001/logic/getlogicall',
// addadult:'http://localhost:3001/logic/addadult',
// // http://localhost:3001/logic/getlogic?adult="+adult+"&checkin="+checkIn+"&checkout="+checkOut',
// actualcheckout:'http://localhost:3001/booking/actualcheckout',
// cancelpolicy:'http://localhost:3001/booking/cancelpolicy',
// forgotpassword:'http://localhost:3001/users/forgotpassword',
// generateOTP:'http://localhost:3001/email/generateOTP?email=',
// verifyOTP:'http://localhost:3001/email/verifyOTP',
// verifyOTPwithemail:'http://localhost:3001/email/verifyOTP',
// getChargedAmenities:'http://localhost:3001/booking/getChargedAmenities',
// getguestbookingstatuscancel:'http://localhost:3001/users/getguestbookingstatuscancel?checkin=',
// getroomslist:'http://localhost:3001/room/getroomslist?bookingid=',


// getroom:'http://localhost:3001/room/getroom',
// getstatus:'http://localhost:3001/room/getstatus?stastustype=',
// roomupdatestatus:'http://localhost:3001/room/roomupdatestatus',
// getroomlist:'http://localhost:3001/booking/getroomlist?adults=',
// getidproofimage:'http://localhost:3001/booking/getidproofimage?bookingid=',
// addebreading:'http://localhost:3001/eb/addebreading',
// getebdata:'http://localhost:3001/eb/getebdata',
// updateebreading:'http://localhost:3001/eb/updateebreading',
// getebreading:'http://localhost:3001/eb/getebreading?bookingid=',
// getguestdetailmonthly:'http://localhost:3001/users/getguestdetailmonthly?checkin=',

// gettariffamount:'http://localhost:3001/users/gettariff',
// updateTariff:'http://localhost:3001/users/updatetariff',
// // getroomlistURL:'http://localhost:3001/users/getroomlist?adults='$adultNumber

// // baseURL:'assets/',
// // roleapiURL:'http://192.168.1.7:3001/users/getrole',

// //pls give ur ipconfig no
// checkRoomAvailable:'http://localhost:3001/room/checkAvailability?roomtypeid'

// };
